Redux: Batch update of 'icons'
oVirt/ovirt-ui-components pull request #13
Opened 2016-10-21 10:29 UTC by mareklibra

As an optimization, icons are provided in an array by
the updateIcons() action.

Useful for reload from LocalStorage.

2016-10-21 13:19 UTC, matobet commented on src/reducers/icons.js
> +function updateOrAddVm ({ state, payload: { icons } }) {
@mareklibra are you really sure you want to call this method `updateOrAddVm`? Seems really icon-centric. If this is a result of a copy-paste from the VM equivalent probably that is a sign that we want to extract this to a separate helper called e.g. `mergeById` and call it from both reducers?

2016-10-21 13:32 UTC, mareklibra commented on src/reducers/icons.js
> +function updateOrAddVm ({ state, payload: { icons } }) {
ooops, thanks

2016-10-21 14:05 UTC, matobet requested changes

2016-10-21 14:05 UTC, matobet commented on src/components/VmDetail/index.js
> +    .filter(msg => { return (msg.failedAction && msg.failedAction.payload && msg.failedAction.payload.vmId === vmId) })
please make lambdas returning single value without the braces and `return`. Just `msg => expression` is sufficient.

2016-10-21 14:05 UTC, matobet commented on src/components/VmDetail/index.js
> +    .sort((msg1, msg2) => { return msg1.time - msg2.time })
same here

2016-10-21 14:06 UTC, matobet approved these changes

2016-10-21 14:07 UTC, matobet approved these changes

2016-10-24 07:40 UTC, mareklibra commented
Done

2016-10-24 10:16 UTC, merged