Full refresh
oVirt/ovirt-ui-components pull request #15
Opened 2016-10-24 11:05 UTC by mareklibra

User can invoke 'Refresh' to fully reload data

2016-10-24 12:10 UTC, matobet commented on src/reducers/vms.js
> +  // and manage references (like for icons). Recently it makes no sense
s/Recently/For now :-)

2016-10-24 12:10 UTC, matobet commented on src/reducers/vms.js
> +function clearVmDisks ({ state, payload: { vmId } }) {
just a question: why do we need to clear a VM's disks?

2016-10-24 12:12 UTC, matobet requested changes

2016-10-24 12:12 UTC, matobet commented on src/reducers/vms.js
> +    .map(vmId => vmId)
the last mapping appears to be a redundant (identity) operation

2016-10-24 13:15 UTC, mareklibra commented on src/reducers/vms.js
> +    .map(vmId => vmId)
Right, left over ...

2016-10-24 13:18 UTC, mareklibra commented
Done

2016-10-26 09:08 UTC, matobet commented on src/reducers/vms.js
> +    .filter(vmId => !vmIdsToPreserve.some(toPreserveId => toPreserveId === vmId))
please consider using a `Set` instead of doing nested linear lookups to check for presence

2016-10-26 12:29 UTC, matobet approved these changes

2016-10-26 12:29 UTC, merged