Add feature for changing console button tooltip to "Console in use"
oVirt/ovirt-ui-components pull request #34
Opened 2017-03-17 10:19 UTC by bond95

2017-03-20 11:18 UTC, matobet commented
This change seems to be in direct conflict with #33 @bond95 do you intend to base one on the other?

2017-03-21 10:57 UTC, matobet requested changes

2017-03-21 10:57 UTC, matobet commented on src/components/VmActions/index.js
> +  if (vm.get('sessions') && vm.get('sessions').filter(c => c.get('consoleUser')).size) {
please use `.isEmpty()` instead of relying on the `size` > 0 causing the condition to be true

2017-03-21 15:07 UTC, matobet commented
@bond95 please rebase and resolve conflicts

2017-03-29 10:52 UTC, mareklibra commented
Rebase is needed because of https://github.com/oVirt/ovirt-ui-components/pull/35.
Please consider moving the components to ovirt-web-ui.

2017-05-25 14:11 UTC, bond95 commented
It is not give a sense to rebase, because all changes was rebased to web-ui.

2017-05-25 14:11 UTC, closed without merging