Autoconnect
oVirt/ovirt-ui-components pull request #38
Opened 2017-04-26 15:17 UTC by bond95

@mareklibra Please review

2017-04-27 07:46 UTC, mareklibra requested changes
Looks good, just minor clean-ups

@bond95 , please rebase on top of clean master branch

2017-04-27 07:46 UTC, mareklibra commented on src/components/Checkbox.js
> +  // let checked = config.get('filter') ? 'checked' : ''
leftover?

2017-04-27 07:46 UTC, mareklibra commented on src/components/Options/ConsoleOptions.js
> +export default ConsoleOptions
new line, please

2017-04-27 07:46 UTC, mareklibra commented on src/index.js
> +export * from './helpers'
new line

2017-04-28 09:49 UTC, bond95 commented
@mareklibra fixed, please review

2017-04-28 11:16 UTC, mareklibra approved these changes

2017-04-28 11:29 UTC, merged